import type { Metadata } from "next"
import "./globals.css"
import ReduxProvider from "@/redux/redux-provider"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body>
          {children}
          <div id="modal-root" />
        </body>
      </ReduxProvider>
    </html>
  )
}
